feat: action skill notebook
watson-developer-cloud/assistant-skill-analysis pull request #39
Opened 2022-06-27 14:12 UTC by tsinggggg

creating skill analysis notebook for action skills

pending credential files for unit tests

2022-06-28 19:15 UTC, tsinggggg commented
Rebased with current master, build passes. Should be ready for review again.

2022-06-28 21:02 UTC, haodeqi requested changes
Hi Cheng, thanks a lot for all the changes. I have a few in-line comments for you. Before we merge this, we should definitely try to run the unittest but also test run the notebooks manually. We will also need to review the documentation of the notebook but that can be done in the next pass.

2022-06-28 21:02 UTC, haodeqi commented on assistant_skill_analysis/utils/skills_util.py
> +    apikey, workspace_id, assistant_id = None, None, None
is this needed for the end user? This will stop the prompt from showing

2022-06-28 21:02 UTC, haodeqi commented on assistant_skill_analysis/utils/skills_util.py
> +        workspace_json.get("dialog_settings", {}).get("actions", "").lower() == "true"
this line raise an error during local testing, let's change this line to:
```
dialog_setting_action_flag = bool(workspace_json.get("dialog_settings", {}).get("actions", False))
```

2022-06-28 21:41 UTC, tsinggggg commented on assistant_skill_analysis/utils/skills_util.py
> +    apikey, workspace_id, assistant_id = None, None, None
Thanks for the feedback! I didn't mean to overwrite the input args. Corrected in new commit.

2022-06-28 21:42 UTC, tsinggggg commented on assistant_skill_analysis/utils/skills_util.py
> +        workspace_json.get("dialog_settings", {}).get("actions", "").lower() == "true"
I ran the notebook with the new commit locally and manually.  Seems to work now.

2022-06-29 14:39 UTC, haodeqi approved these changes
Looks good to me. Thank you Cheng.

2022-06-29 14:39 UTC, merged